export const TIMING_THRESHOLDS = {
  // Reveal beats in milliseconds
  REVEAL_BEAT_1_CLOSED_BOX_MS: 1200,
  REVEAL_BEAT_2_BOX_SHAKES_MS: 1200,
  REVEAL_BEAT_3_BOX_OPENS_MS: 1000,
  REVEAL_BEAT_4_RESULT_APPEARS_MS: 1800,
  REVEAL_BEAT_5_VOTE_BREAKDOWN_MS: 2000,
  REVEAL_BEAT_6_MIND_CHANGES_MS: 2500,

  // Discussion tension stages in seconds remaining
  DISCUSSION_TENSION_CALM_THRESHOLD: 40,
  DISCUSSION_TENSION_PULSE_THRESHOLD: 20,
  DISCUSSION_TENSION_RAPID_TICK_THRESHOLD: 10,

  // Post-Round Auto-Advance Timer
  INTERSTITIAL_AUTO_ADVANCE_SECONDS: 6,
} as const;
